.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "/Users/alexchuang/Documents/flashkv0516/temp/llama_roadB/llama.cpp-master/build-flat/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal"
.globl _ggml_metallib_end
_ggml_metallib_end:
